// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

function GetSum(fibonacci) {
    let sumOfEvenNumbers = 0 
    let current = 1; 
    let next = 2; 
    
    for (current; current < fibonacci;) {

        if ((current + next) % 2 === 0) { 
            sumOfEvenNumbers += (current + next)
            console.log(sumOfEvenNumbers)
        }
        current = next; 
        next += current;
    }
    return sumOfEvenNumbers;
}
console.log(GetSum(5))

